# FROM HERE
# https://hub.docker.com/r/x11docker/gnome/dockerfile

# podman build --tag debian_buster_x ./Dockerfile_xBuster
# x11docker/gnome
# 
# Run Gnome 3 desktop in docker. 
# Use x11docker to run image: 
#   https://github.com/mviereck/x11docker 
#
# Examples: 
#  - Run desktop:
#      x11docker --desktop --init=systemd -- x11docker/gnome
#  - Run single application:
#      x11docker x11docker/gnome gedit
#
# Options:
#   Persistent home folder stored on host with   --home
#   Shared host file or folder with              --share PATH
#   Hardware acceleration with option            --gpu
#   Clipboard sharing with option                --clipboard
#   ALSA sound support with option               --alsa
#   Pulseaudio sound support with option         --pulseaudio
#   Language locale setting with option          --lang [=$LANG]
#   Printer support over CUPS with option        --printer
#   Webcam support with option                   --webcam
#
# See x11docker --help for further options.
#
# Known issues:
#  - Many shell extensions do not work properly.
#  - gnome-control-center hangs for a while at some entries.
#  - gnome-usage crashes with a segfault.
#  - Wayland setups do not work.

FROM debian:bookworm-20231120-slim
ENV LANG en_US.UTF-8
ENV SHELL=/bin/bash


# FROM HERE
# https://stackoverflow.com/questions/56757169/is-there-a-way-to-suppress-update-alternatives-warning-skip-creation-warning
# exclude /usr/share/* data
RUN \
    echo 'path-exclude /usr/share/doc/*' >/etc/dpkg/dpkg.cfg.d/docker-minimal && \ 
    echo 'path-exclude /usr/share/man/*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal && \
    echo 'path-exclude /usr/share/groff/*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal && \
    echo 'path-exclude /usr/share/info/*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal && \
    echo 'path-exclude /usr/share/lintian/*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal && \
    echo 'path-exclude /usr/share/linda/*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal && \
    echo 'path-exclude /usr/share/locale/*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal && \
    echo 'path-include /usr/share/locale/en*' >>/etc/dpkg/dpkg.cfg.d/docker-minimal


# cleanup script for use after apt-get
RUN echo '#! /bin/sh\n\
    env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y\n\
    apt-get clean\n\
    find /var/lib/apt/lists -type f -delete\n\
    find /var/cache -type f -delete\n\
    find /var/log -type f -delete\n\
    exit 0\n\
    ' > /cleanup && chmod +x /cleanup

RUN \
    apt-get update && \
    apt-get install -y locales apt-utils 
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen 
RUN dpkg-reconfigure locales 
RUN update-locale LANG="en_US.UTF-8 UTF-8"
ENV LANG "en_US.UTF-8 UTF-8"



# basics
RUN apt-get update && \
    # env DEBIAN_FRONTEND=noninteractive apt-get install -qq --no-install-recommends \
    # locales && \
    # echo "$LANG UTF-8" >> /etc/locale.gen && \
    # locale-gen && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -qq --no-install-recommends \
    at-spi2-core \
    dbus \
    dbus-x11 \
    libpulse0 \
    procps \
    psutils \
    systemd \
    x11-xserver-utils 
# /cleanup

# Gnome 3
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    gnome-session  
# /cleanup

# Gnome 3 apps
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    # cheese \
    # gedit \
    # gnome-control-center \
    # gnome-system-monitor \
    # gnome-terminal \
    # gnome-tweak-tool \
    # nautilus && \
    # old gnome-session-xsession \
    gnome-control-center \
    gnome-system-monitor \
    gnome-session-bin \
    gnome-extensions-app \
    xvfb \
    # old xorg-x11-server-Xvfb \
    gnome-terminal \ 
    xdotool \ 
    xautomation \ 
    sudo 
# /cleanup


# Gnome Shell extensions
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    gnome-shell-extension* 
# /cleanup

# tigervnc-standalone-server
# FROM HERE
# https://www.server-world.info/en/note?os=Debian_12&p=desktop&f=6
RUN apt-get update && \
    # env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y  \
    tigervnc-standalone-server && \
    # tigervnc-common && \
    # tigervnc-tools && \
    xterm && \
    /cleanup

# tigervncserver -xstartup /usr/bin/xterm -geometry 800x600 -localhost no :1


RUN apt-get update && \
    # env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y  \
    iproute2 && \
    /cleanup

## Workaround to get gnome-session running. 
## gnome-session fails if started directly. Running gnome-shell only works, but lacks configuration support.
# RUN apt-get update && \
#    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
#      guake && \
#    rm /usr/share/applications/guake.desktop /usr/share/applications/guake-prefs.desktop && \
#    echo "#! /bin/bash\n\
#guake -e gnome-session\n\
#while pgrep gnome-shell; do sleep 1 ; done\n\
#" >/usr/local/bin/startgnome && \
#    chmod +x /usr/local/bin/startgnome && \
#    /cleanup

# Copy system configuration.
COPY etc /etc

# Start Xvfb via systemd on display :99.
# Add the gnomeshell user with no password.
RUN systemctl unmask systemd-logind.service console-getty.service getty.target && \
    systemctl enable xvfb@:99.service && \
    systemctl set-default multi-user.target

#RUN adduser -m -U -G users,adm gnomeshell && \
#    echo "gnomeshell     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# RUN adduser gnomeshell && \
#    usermod -aG users,adm gnomeshell && \\
#    echo "gnomeshell     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# # useradd warning: gnomeshell's uid 1001 is greater than SYS_UID_MAX 999
RUN useradd -rm -d /home/gnomeshell -s /bin/bash -g root -G sudo -u 777 gnomeshell 

RUN echo "gnomeshell     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Add the scripts.
COPY bin /usr/local/bin

CMD [ "/usr/sbin/init", "systemd.unified_cgroup_hierarchy=0" ]


# CMD /usr/local/bin/startgnome